### ISSUE TITLE
YouTube load persists, but does not load

### ISSUE THREAD

**Issue by davideveland** [UDayton/interactivevideo-quiz#4]
We have not made any changes to our Tsugi app store link, but the Interactive Tool as hosted - doesn't permit us to add a YT video presently. It has worked just fine in the past, and it continues to work for Warpwire video content. I have tested this on Chrome and Safari. Any suggestions? https://www.dropbox.com/s/iilvhlgs59r980r/Screen%20Shot%202021-08-18%20at%209.23.52%20AM.png?dl=0

**Comment by davideveland** [comment]
Nevermind, it looks like it doesn't parse the shortened form of a Youtube link for example this does not work: https://youtu.be/NZjIzk4POb0, but this does: https://www.youtube.com/watch?v=NZjIzk4POb0

**Comment by davidpbauer** [comment]
Correct, the tool was written with the assumption that the full url with the video id (after v=) included.
